motor_names:
  - master_motor

# motor name
master_motor:
  # epos's node information (must be enough to identify the node)
  device: 'EPOS4' # default: 'EPOS4'
  protocol_stack: 'MAXON SERIAL V2' # default: 'MAXON SERIAL V2'
  interface: 'USB' # default: 'USB'
  port: 'USB0' # default: 'USB0'
  node_id: 1 # default: 0 (invalid)

  # communication settings (optional)
  # 'device' is a set of types of device, protocol_stack, interface, and port.
  # order of node initialization is that of commandline arguments.
  baudrate: 1000000 # default: 0 (keep current baudrate)
  timeout: 500 # [ms], default: 0 (keep current timeout)

  # general parameters (optional)
  use_ros_unit: false # use ros standard units (rad, rad/s, Nm) in hardware interfaces
                      # or epos standard units (quad count of encoder pulse(qc), rpm, mNm)
                      # (default: false)

  # epos's operation mode (required)
  control_mode: "profile_position" # optional to "profile_velocity" and "current"

  # encoder parameters (required)
  encoder:
    type: 2 # 1: INC 3CH, 2: INC 2CH, 4: SSI ABS BIN, 5: SSI ABS GRY
    resolution: 2048 # encoder resolution
    gear_ratio: 18 # gear ratio of motor
    inverted_polarity: false

  # profile position mode configs (optional)
  profile_position:
    velocity: 2000 # [rpm] #tested on 21/12/2021
    acceleration: 8000 # [rpm/s]
    deceleration: 9000 # [rpm/s]
    
  # profile position mode configs (optional)
  profile_velocity:
    velocity: 200 # [rpm]
    acceleration: 8000 # [rpm/s]
    deceleration: 9000 # [rpm/s]



